name: attendance

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:

        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Deploy and run setup on server via SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/pratik/githubaction_prac/attendance-server-master/attendance-server
          python3 -m venv git
          source git/bin/activate

          python -m pip install --upgrade pip
          pip install -r requirements.txt

          python manage.py collectstatic --noinput
          python manage.py makemigrations
          python manage.py migrate
          python manage.py createsuperuser --noinput --username pratik || true

          pkill gunicorn || true
          gunicorn --bind 0.0.0.0:8000 main.wsgi:application --workers 3 --daemon

    - name: Deploy and run Nginx via Docker
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/nginx-app:latest
          docker stop nginx-container || true
          docker rm nginx-container || true
          docker run -d --name nginx-container -p 80:80 \
            ${{ secrets.DOCKER_USERNAME }}/nginx-app:latest
