name: attendance

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.8.10
      uses: actions/setup-python@v4
      with:
        python-version: 3.8.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Django tasks
      run: |
        python manage.py collectstatic --noinput
        python manage.py migrate
        python manage.py test

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Django image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/django-container1:latest -f attendance-server/Dockerfile .
        docker push ${{ secrets.DOCKER_USERNAME }}/django-container1:latest

    - name: Build and push Nginx image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/nginx-app:latest -f attendance-server/Dockerfile attendance-server/
        docker push ${{ secrets.DOCKER_USERNAME }}/nginx-app:latest

    - name: Deploy to server via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/django-container1:latest
          docker pull ${{ secrets.DOCKER_USERNAME }}/nginx-app:latest

          docker network create attendance-network || true

          docker stop django-container || true
          docker rm django-container || true
          docker run -d --name django-container1 --network attendance-network \
            ${{ secrets.DOCKER_USERNAME }}/django-container1:latest

          docker stop nginx-container || true
          docker rm nginx-container || true
          docker run -d --name nginx-container --network attendance-network -p 80:80 \
            ${{ secrets.DOCKER_USERNAME }}/nginx-app:latest
