name: attendance

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-24.0.4.2

    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # - name: Build and push Nginx image
    #   run: |
    #     docker build -t ${{ secrets.DOCKER_USERNAME }}/nginx-app:latest -f attendance-server/Dockerfile attendance-server/
    #     docker push ${{ secrets.DOCKER_USERNAME }}/nginx-app:latest

    - name: Deploy to server via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        
    - name: Create and run virtual environment 
      run: |
        cd home/pratik/githubaction_prac/attendance-server-master/attendance-server
        cd usr/src/Python-3.8.2
        python3 -m venv git
        source git/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run deployment script   
      run: |
        python manage.py collectstatic --noinput
        python manage.py makemigrations
        python manage.py migrate
        python manage.py createsuperuser --noinput --username pratik 
        pkill gunicorn || true
        gunicorn --bind 0.0.0.0:8000 main.wsgi:application --workers 3 --daemon

    - name: Pull and run Nginx container
      run: |
        docker pull ${{ secrets.DOCKER_USERNAME }}/nginx-app:latest
        docker stop nginx-container || true
        docker rm nginx-container || true
        docker run -d --name nginx-container -p 80:80 \
        ${{ secrets.DOCKER_USERNAME }}/nginx-app:latest
